### ISSUE TITLE
Running `pbfetch` fails due to `FileNotFoundError'

### ISSUE THREAD

**Issue by Peregrine05** [pennybelle/pbfetch#28]
The full error is:
```
`FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/pbfetch/config/config.txt'`
```

This is likely due to Python not having superuser permissions when installing via `pip install pbfetch`. A password should be requested during installation to grant this permission, but that is not currently done.

> I don't know either, but I think the key is `setuptools` and a `setup.py` file.

**Comment by morr0ne** [comment]
Thank you for your suggestion, however, `setuptools` and `setup.py` are not suitable solutions in this case. The project is already using rye and follows modern packaging standards.

Using a setup script that requires root access would pose significant security risks and is beyond the scope of what a package should handle. Managing system-wide directories, such as the share directory, should be the responsibility of the distribution's package manager.

A better approach would be to either:
- Not provide a default configuration: This would force users of the pip package to manually copy or create a configuration file themselves.
- Embed the default configuration within the script: This would eliminate the dependency on the share directory and simplify configuration management.

Handling the "file not found" error more gracefully by printing a warning message is probably be a good idea regardless. This way, we can inform the user that a configuration is needed, preventing the program from crashing unexpectedly.

**Comment by pennybelle** [comment]
Good idea regarding embedding the default config into the script itself. This simplifies everything for the user and myself, and I just pushed an update with this change. The `/usr/share` directory is no longer affected by pbfetch.
